services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: mentor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mentor
    volumes:
     - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: